#!/bin/sh
echo "🔍 Running pre-commit checks..."
# Run lint-staged to lint and format only staged files
npx lint-staged

# Adding Node.js package checks pre-commit script
./.githooks/package-checker-node

# Build the project
npm run build

echo "✅ Pre-commit checks completed successfully!"